name: Docker Image CI

on:
   push:
      branches: ["main"]

jobs:
   build: 
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
           DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
           DOCKER_PASSWORD: ${{secrets.DOCKER_PASS
        run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
           
      - name: Build the Docker Image
        run: docker build -t nj-php-repo .
      - name: Push to Docker Hub
        run: docker push nijeshb/nj-hi:latest
        #run: docker build . --file Dockerfile --tag nj-hi:${date +%s}
   
      
